version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    command:
      #- --innodb_force_recovery=0
      - --default_time_zone=America/Sao_Paulo
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
