@baseUrl = http://localhost:3000

### Recados
GET {{baseUrl}}/recados/
?limit=50
&offset=0
Authorization: Bearer 123456

### Lista um recado
GET {{baseUrl}}/recados/58/

### Cria recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo recado",
    "deId": 1,
    "paraId": 1
}

### Atualiza um recado
PATCH  {{baseUrl}}/recados/7
Content-Type: application/json

{
    "texto": "texto atualizado!",
    "lido": false
}

### Apaga um recado
DELETE  {{baseUrl}}/recados/3/





### Pessoas
GET {{baseUrl}}/pessoas/
?limit=100
&offset=100

### Lista uma pessoa
GET {{baseUrl}}/pessoas/1/

### Cria Pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "email2@gmail.com",
    "password": "123456",
    "nome": "Rodrigo"
}

### Atualiza uma Pessoa
PATCH  {{baseUrl}}/pessoas/4
Content-Type: application/json

{
    "password": "1234567",
    "nome": "Rodrigo"
}

### Apaga uma Pessoa
DELETE  {{baseUrl}}/pessoas/10/





### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/

### Exemplo de rota
# @name AppControllerGetExemplo
GET {{baseUrl}}/home/exemplo

### AppControllerGetExemplo
# @name AppControllerGetExemplo
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController
# @name ConceitosAutomaticoController
GET {{baseUrl}}/conceitos-automatico/
