services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      - "POSTGRES_USER=${DATABASE_USERNAME}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_USERNAME}"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: unless-stopped

volumes:
  postgres_data: